### ISSUE TITLE
[Bug] Can't generate aggregate features without transformations

### ISSUE THREAD

**Issue by rohan-gt** [FeatureLabs/featuretools#1033]
Running `dfs()` without passing the optional `'trans_primitives'` parameter throws the following error:

`AssertionError: features must be a non-empty list of features`

Is there a way I can aggregate my data without applying any transformations?

**Comment by rwedge** [comment]
Hi @rohan-gt ,

If you use `features_only=True` when you run `dfs`, does it return any features?  If not, `dfs` is not creating any features, which is why this error is popping up when it tries to calculate the feature values.

This could be happening due to the data types of your dataset.  Each aggregation primitive can only be applied to certain data types.  If the child entity doesn't have the input data types used by the aggregation primitives, no aggregation features will be made.  Adding transform primitives can result in new features being created that are the right data type for the aggregation, resulting in aggregation features only appearing if transform primitives are also used.
