### ISSUE TITLE
Add dask (and koalas in future) as optional requirement

### ISSUE THREAD

**Issue by candalfigomoro** [FeatureLabs/featuretools#1037]
In the code I see statements such as `import dask.dataframe as dd`, how does it behave when Dask is not installed?

Maybe we should use something like this https://stackoverflow.com/a/52826085 to handle cases where Dask is not installed.

I think we should also add add "dask" as "extras_require" in the setup.py file (see https://github.com/FeatureLabs/featuretools/blob/master/setup.py#L9) and remove it from install requirements, since not everybody needs Dask support.

The same approach should probably be used when Koalas dataframes support will be merged.

**Comment by thehomebrewnerd** [comment]
If Dask is not installed, this will generate a `ModuleNotFound` error when importing `featuretools`. However, starting with version 0.16.0 of Featuretools, Dask will be installed automatically when Featuretools is installed. In that case, in order for the error to be generated, a user would have to uninstall Dask after installing Featuretools.

**Comment by rwedge** [comment]
Since Featuretools uses dask in its general `n_jobs` approach, dask has been a requirement for years before adding dask dataframe support.

Featuretools has an `import_or_raise` method used to handle importing optional requirements in the code.  We could use this for the koalas code and make koalas an extra.
https://github.com/FeatureLabs/featuretools/blob/95117a7da15decf993bde65479f67fe883072754/featuretools/utils/gen_utils.py#L76-L88

**Comment by candalfigomoro** [comment]
> Since Featuretools uses dask in its general `n_jobs` approach, dask has been a requirement for years before adding dask dataframe support.

Ok, I thought it was only necessary for Dask dataframes support.

So this is only relevant when Koalas support will be merged to avoid having Koalas as a hard dependency.
