### ISSUE TITLE
Built-in subtract_numeric primitive ignores certain variables

### ISSUE THREAD

**Issue by KatyZhao** [FeatureLabs/featuretools#1075]
### Bug/Feature Request Title
Built-in subtract_numeric primitive ignores certain variables

-----

featurestools version: 0.17.0
python version: Python 3.6.10

#### Bug/Feature Request Description
1. Prepare the entityset 
```
data = {"index": [0, 1, 2],
        "a": [1, -2, 3.8],
        "b": [4, 15, 6.2],
        "c": [2.3, 2, 0],
        "d": [-9, 0, np.nan]}

df = pd.DataFrame(data=data)

es = ft.EntitySet(id="es")
es = es.entity_from_dataframe(entity_id="test",
                              dataframe=df,
                              index="index")
```
2. Create a custom primitive for subtraction (which has the same function definition as built-in primitive `subtract_numeric`)
```
def basic_subtract(subtrahend, minuend):
    return np.subtract(subtrahend, minuend)

BasicSubtract = make_trans_primitive(function=basic_subtract, input_types=[Numeric, Numeric], return_type=Numeric)
```
3. DFS
```
feature_matrix, feature_defs = ft.dfs(entityset=es, target_entity="test",
                                      trans_primitives=[
                                                        "subtract_numeric",
                                                        BasicSubtract
                                                        ], 
                                      primitive_options={
                                            "subtract_numeric": [{  
                                                          "include_variables": {"test": ["a", "d"]}
                                                        },
                                                        {
                                                            "include_variables": {"test": ["b", "c"]}
                                                        }],
                                            BasicSubtract: [{  
                                                          "include_variables": {"test": ["a", "d"]}
                                                        },
                                                        {
                                                            "include_variables": {"test": ["b", "c"]}
                                                        }],
                                            
                                      },
                                      max_depth = 2,
                                      )
```

#### Actual Output
![image](https://user-images.githubusercontent.com/36015810/88023572-43baac80-caff-11ea-88fc-353ae1ea8a9e.png)

#### Expected Output
Both `subtract_numeric` and `BasicSubtract` should create 4 features while `subtract_numeric` ignores variable `d`.

**Comment by thehomebrewnerd** [comment]
Based on a quick investigation, this appears to be related to the `commutative` parameter. If the `BasicSubtract` custom primitive is defined with `commutative=True`, the results match what is returned from the `SubtractNumeric` primitive which has `commutative=True` by default.

**Comment by thehomebrewnerd** [comment]
Also, I'm wondering why commutative is `True` for subtract numeric, since `x - y` is not the same as `y - x`.

**Comment by couyang24** [comment]
> Also, I'm wondering why commutative defaults to `True` for subtract numeric, since `x - y` is not the same as `y - x`.

In this case, `subtract_numeric` with specified the `x - y`, commutative equals `True` does not really make sense. However, if nothing is specified, commutative equals `True` makes sense since there would be a duplicate for every combination. By setting commutative equals `True` would keep each combination unique.

**Comment by couyang24** [comment]
## Reason of the issue:
Also, I have found some information and hope that can help you navigate the problem. As you probably already know, the commutative function is affecting `match` function. In the `match` function, `commutative=True` is only used in this [part](https://github.com/FeatureLabs/featuretools/blob/main/featuretools/synthesis/deep_feature_synthesis.py#L874-L881). 

```
            new_match = [m] + list(r)

            # commutative uses frozenset instead of tuple because it doesn't
            # want multiple orderings of the same input
            if commutative: # First Part
                new_match = frozenset(new_match)
            else:
                new_match = tuple(new_match)
            matching_inputs.add(new_match)

    if commutative: # Second Part
        matching_inputs = {tuple(sorted(s, key=lambda x: x.get_name().lower())) for s in matching_inputs}
```
`new_match` create each combination of every feature. If `commutative=False`, it would use tuple and skip the second part (labelled in the code above) and thus keep the combination in its original order in `matching_inputs`.
For example, `{(<Feature: A>, <Feature: B>), (<Feature: B>,<Feature: A>)}`

When `commutative=False`, the frozenset would randomly return the order of the two features. See example [here](https://stackoverflow.com/questions/52768966/is-iterating-over-the-same-frozenset-guaranteed-always-to-produce-the-items-in-t). If without the second part, it would return either `{(<Feature: A>, <Feature: B>)}` or `{(<Feature: B>,<Feature: A>)}`. With the second part, `sorted` would only return the features following alphabetical order of the feature name and only return `{(<Feature: A>, <Feature: B>)}`. 

Then, `match` function is used in `_get_matching_inputs` function, which is [here](https://github.com/FeatureLabs/featuretools/blob/45998e8f119fbafd6143bfb2313492bb294ab8aa/featuretools/synthesis/deep_feature_synthesis.py#L775-L795).

The key is this line of code.
```
matching_inputs = filter_matches_by_options(matching_inputs, primitive_options)
```
The input `matching_inputs` is in this example, `{(<Feature: A>, <Feature: B>)}` if `commutative=True` or `{(<Feature: A>, <Feature: B>), (<Feature: B>,<Feature: A>)}` if `commutative=False`.

The `primitive_options` would be original order we specified. In this case, if we say `B-A`, it would be 
```[{'include_variables': {'test': {'B'}}, 'ignore_variables': {}, 'ignore_entities': set()}, {'include_variables': {'test': {'A'}}, 'ignore_variables': {}, 'ignore_entities': set()}]```

Which means, it would search for feature B in any combination in the first position and feature A in the second position. As I mentioned before, if `commutative=False`, we would get `{(<Feature: A>, <Feature: B>), (<Feature: B>,<Feature: A>)}` and this would return `{(<Feature: B>, <Feature: A>)}` and create the transformation that we required. But in the case `commutative=True`, it can be found feature B in the first position and A in the second position since the order is `{(<Feature: A>, <Feature: B>)}`, it would not return any transformation.

## Potential Solutions:
1. `commutative` should be set to be `False` if the the order of the transformation is give rather than `True` for all `subtract_numeric`
2. `primitive_options` can search for both features in both positions for which in this case is searching feature A and B in position 1 and do that again in position 2.

## Additional:
In the `match` function, since part 2 - `sorted` in a set, is already doing remove duplication work, frozenset is not really needed. we can just do `new_mach = tuple([m]+list(r))`
