### ISSUE TITLE
Question: custom primitives from specific fields in an EntitySet

### ISSUE THREAD

**Issue by brilhana** [FeatureLabs/featuretools#1104]
For example, my EntitySet has the fields `a` (numeric), `b` (numeric), `c` (numeric), `d` (categorical). and given the dummy primitive:

```python
from featuretools.primitives import make_trans_primitive
from featuretools.variable_types import Numeric

def dummy(x, y):
    return x / y

Dummy = make_trans_primitive(function=dummy, input_types=[Numeric, Numeric], return_type=Numeric)
```

This dummy primitive would be computed for every permutation of `a`, `b` and `c`? i.e. `(a, b)`, `(a, c)`, `(b, a)`, `(b, c)`, `(c, a)`, `(c, b)`. Is there any way to restrict that computation to `a` and `b`?

**Comment by thehomebrewnerd** [comment]
Yes, you can do this type of thing using the `primitive_options` parameter when you call `dfs`. If you had an entityset named `es` with a target entity named `entity` you could specify `primitive_options` as shown below. This would cause the `Dummy` primitive to create features for `a / b` and `b / a`, but would not create any features involving `c`.

```
ft.dfs(entityset=es,
       target_entity='entity',
       trans_primitives=[Dummy], 
       primitive_options={
           Dummy: [
               {'include_variables': {'entity': ['a', 'b']}},
               {'include_variables': {'entity': ['a', 'b']}}
           ]})
````

The primitive options specification can be a little confusing to read at first, but since your `Dummy` primitive has two inputs, you need to specify the `include_variables` option for each of the inputs. So in this case you are defining options for the Dummy primitive. The first item in the list is specifying which variables to use for the first input, and the second item in the list is specifying the inputs to use for the second input. In `include_variables` we are telling featuretools to only use variables `a` and `b` from the Entity named `entity` for both of the inputs. 

If you wanted only to return the result of `b / a`, you could change the `primitive_options` to this instead:

```
ft.dfs(entityset=es,
       target_entity='entity',
       trans_primitives=[Dummy], 
       primitive_options={
           Dummy: [
               {'include_variables': {'entity': ['b']}},
               {'include_variables': {'entity': ['a']}}
           ]})
```

**Comment by brilhana** [comment]
Thanks!
