### ISSUE TITLE
duplicate in time_index

### ISSUE THREAD

**Issue by mz2sj** [FeatureLabs/featuretools#1116]
hi~
I have time series data where time duplicates like this
![image](https://user-images.githubusercontent.com/26783514/90774578-44c34180-e32a-11ea-8378-7d729512ad23.png)
when I set time_index='date_time,I meet this error
`AssertionError: Index is not unique on dataframe (Entity train_op)`
How can I solve this problem if time_index is not unique?
Thank you!

**Comment by rwedge** [comment]
@mz2sj , it should be fine to have duplicate values in a time index.  That assertion error happens if the index column has duplicate values.  There's probably been an issue setting the `index`. 

For featuretools the `index` refers to column that uniquely identifies each row in the table, and the `time_index` is the column that identifies at what time the data in the row became known.

If you didn't use the `index` parameter Featuretools will try to use the first column of the dataframe as the index, so if that isn't unique it will raise an error.

**Comment by mz2sj** [comment]
Thank you for your reply！My table is user's operation like below,
![image](https://user-images.githubusercontent.com/26783514/90842162-29d7e800-e391-11ea-92f7-35fa7407df30.png)
One user may  has several operation at the same,so the user index column has duplicate values.The user column is also the primary key linking to other tables.Shoud I make a unique key for train_op?
Thank you !

**Comment by rwedge** [comment]
@mz2sj , yes I would make a unique key for train_op.

If it helps, `entity_from_dataframe` can create a column with a unique key and set that as the index.  Add the optinal `make_index=True` and for the `index` option, set the name you would like for the new column.  An example where the new column is named "op_id":
```python
es = es.entity_from_dataframe(
    entity_id="train_op"
    dataframe=train_op,
    make_index=True,
    index="op_id",
    time_index="date_time"
) 
```

Hope that helps!

**Comment by mz2sj** [comment]
Thank you！I’ll try it！

**Comment by rwedge** [comment]
Closing this issue for now since the question seems answered.  Feel free to re-open, or ask questions on our [slack channel](https://join.slack.com/t/featuretools/shared_invite/enQtNTEwODEzOTEwMjg4LTQ1MjZlOWFmZDk2YzAwMjEzNTkwZTZkN2NmOGFjOGI4YzE5OGMyMGM5NGIxNTE4NjkzYWI3OWEwZjkyZGExYmQ).
