### ISSUE TITLE
ValueError: Variable types cannot be inferred from Dask DataFrames, use variable_types to provide type metadata for entity

### ISSUE THREAD

**Issue by gautambak** [FeatureLabs/featuretools#1185]
Hi There

I was using dask dataframes with featuretools because I wanted to see if it can help me ovecome the memory problems I'm having when using pandas df.

I took my dataframe and converted it to a dask dataframe:

df[cats] = converterdDF[cats].astype('category')
df[NumericColumns] = converterdDF[NumericColumns].astype('float64')
dask_df = dd.from_pandas(df, npartitions=2)

then pass it to featuretools : 

es = ft.EntitySet(id="dask_es")
es = es.entity_from_dataframe(entity_id="dask_entity", dataframe=dask_df, index="ticker" ) 

but I get this error:
ValueError: Variable types cannot be inferred from Dask DataFrames, use variable_types to provide type metadata for entity

I am not sure what to do and manually adding the columns is a bit difficult since it's over 100 columns.

Has anyone experienced a similar issue? or provide any advice?

**Comment by gautambak** [comment]
I think I figured it out
dt.update(dict.fromkeys(cat, ft.variable_types.Categorical))  
dt.update(dict.fromkeys(NumericColumns, ft.variable_types.Numeric))

then updating this line seemed to have fixed it

es = es.entity_from_dataframe(entity_id="dask_entity", dataframe=dask_df, index="ticker", variable_types = dt)

**Comment by thehomebrewnerd** [comment]
@gautambak Thank you for reaching out with this issue, and glad to hear you were able to resolve the issue successfully.

As you discovered the current implementation in Featuretools does not perform type inference if a Dask DataFrame is used when creating an Entity. This is because performing type inference requires pulling the data into memory to access the column values. As a result, users are currently required to manually specify variable types for all columns in the Entity.

For reference, this guide provides some additional information on using Dask DataFrames with Featuretools: https://featuretools.alteryx.com/en/stable/guides/using_dask_entitysets.html

Please let us know if you find any additional issues.
