### ISSUE TITLE
Is the full dataset visible to agg primitives?

### ISSUE THREAD

**Issue by aakansh9** [FeatureLabs/featuretools#764]
Does featuretools support agg primitives which are a function of both the groupby chunk as well as the whole column? 

For example, if one wants to make an aggregation feature like - 

```
def mean_encoding(x):
  return ( mean(x) * len(x) + 5 * mean(x_full) )/( len(x) + len(x_full) )
```
Here x is the groupby chunk on which agg primitives usually act and x_full above is the full column from which x is taken.

In general, is the full dataset visible to agg primitives?

-----
*Issues created here on Github are for bugs or feature requests. For usage questions and questions about errors, please ask on Stack Overflow with the [featuretools](https://stackoverflow.com/questions/tagged/featuretools) tag. Check the [documentation](https://docs.featuretools.com/#get-help) for further guidance on where to ask your question.*

**Comment by thehomebrewnerd** [comment]
@aakansh9 It is not currently possible to perform this calculation directly with an aggregation primitive, since the grouping happens outside of the primitive. There is, however, a way that you can perform this type of calculation with a transform primitive.

To do this, you can create a transform primitive that accepts the entire list of numeric values you want to use for the calculation, along with categorical labels that can be used to perform the grouping operations.

To start, define a function to perform the calculation you have specified using the data stored in `x` and the categorical labels in `labels`:

```
def mean_encoding(x, labels):   
    df = pd.DataFrame({'x': x, 'label': labels})
    mean_full = x.mean()
    len_full = len(x)
    grouped_df = df.groupby('label')
    grouped_len = grouped_df.count()
    grouped_len.columns = ['x_len']
    grouped_mean = grouped_df.mean()
    grouped_mean.columns = ['x_mean']
    df = df.merge(grouped_len, on='label', how='left').merge(grouped_mean, on='label', how='left')
    df['output'] = (df['x_mean'] * df['x_len'] + 5 * mean_full)/(df['x_len'] + len_full)
    return df['output']
```
After you have defined the function, you can create the primitive with the `make_trans_primitive` function. Be sure to set `uses_full_entity` to `True` so that Featuretools knows to pass all available entity data to the primitive.   Normally Featuretools only uses the data related to instances that share the same cutoff time, so it is not guaranteed that all available entity data will be present.
```
MeanEncoding = make_trans_primitive(function=mean_encoding,
    input_types=[Numeric, Categorical],
    return_type=Numeric,
    cls_attributes={'uses_full_entity':True})
```
Finally, you can use this primitive in your call to `dfs` to create the custom encoded feature. You will need to update the `entityset` and `target_entity` values appropriately for your setup.
```
feature_matrix, _ = ft.dfs(
    entityset=es,
    target_entity="example_entity",
    agg_primitives=[],
    trans_primitives=[MeanEncoding],
)
```
I am attaching a Jupyter Notebook that contains a full example on how to do this on both a simple test dataframe as well as a more realistic customer transactions entityset.

[mean_encoding_example.ipynb.zip](https://github.com/FeatureLabs/featuretools/files/3767400/mean_encoding_example.ipynb.zip)

**Comment by rwedge** [comment]
Looks like the question was addressed, closing
