### ISSUE TITLE
Feature Primitives - Documentation

### ISSUE THREAD

**Issue by ablacke-ayx** [FeatureLabs/featuretools#778]
Introduction should include an example and how to list the primitives. To improve the user experience.

ft.list_primitives().head(5)

ft.list_primitives().tail(5)

**Comment by kmax12** [comment]
When you say introduction, do you mean the home page of the docs? The user won't really understand primitives until they understand deep feature synthesis, which is why we don't currently  demonstrate it on the home page. 

we currently have an example on [the page](https://docs.featuretools.com/automated_feature_engineering/primitives.html#aggregation-vs-transform-primitive) introducing primitives. 

perhaps we could add a link to that page in the "What's Next" section of the home page introduction? and then also improve that example on that page to be more prominent if we think users are missing it

**Comment by ablacke-ayx** [comment]
Feature primitives are the building blocks of Featuretools. They define individual computations that can be applied to raw datasets to create new features. Because a primitive only constrains the input and output data types, they can be applied across datasets and can stack to create new calculations. **Some examples of primitives that you may already be used to using are MIN, MAX, MODE, STDEV.** 

Many of the applied Data Scientists I have spoken with need the additional context of what a primitive is.
