### ISSUE TITLE
How is `DIFF` calculated?

### ISSUE THREAD

**Issue by rightx2** [FeatureLabs/featuretools#809]
I read [docs](https://docs.featuretools.com/en/stable/generated/featuretools.primitives.Diff.html) but can't understand how does `DIFF` calculate its value.

This part of my example:

![Screen Shot 2019-11-12 at 22 00 07](https://user-images.githubusercontent.com/10606994/68673753-cdd96b00-0597-11ea-8d32-6eec8b5cfb5e.png)

I generated this dataframe using `dfs(..., time_window=None)`

(`time` in index is meaning `cutoff_time`)

What I can't understand is, `DIFF(MAX(sales.amount))` will be calculated by applying `DIFF` on `MAX(sales.amount)` but  since `MAX(sales.amount)` is an aggregated value, which would be only one single value(=max value before cutoff time), how does `DIFF` calculate its value? I think that `DIFF` requires at least 2 values to calculate?...

If I missed something, please let me know how is first value of `DIFF(MAX(sales.amount))`, 25714.287, calculated..

Thanks

**Comment by soliverc** [comment]
I'm also wondering how this works.

I have a dataframe that includes each person's quality of health (from 0 to 100)

e.g.:

`John: 7`
`Mary: 2`
`Paul: 4`

etc etc.

I noticed a DIFF(HealthQuality) variable created by featuretools. Difference between what exactly? I can't figure it out. 

According to the docs, this is what DIFF does:

"Compute the difference between the value in a list and the previous value in that list." What list?

**Comment by rwedge** [comment]
When we apply DIFF to a column we take the value in a row and subtract the value of the previous row from it.  So in the HealthQuality example, DIFF(HealthQuality) for Paul would be the health quality for Paul (40) - the health quality for Mary (20), so 20.  Note that this is based on the order of the data in the entity, not on the order of rows in the final matrix.

I looked into how DIFF was calculated and the results were not what I expected.

As an example, let's look at computing DIFF for the "value" variable of the log entity in the mock entityset.

Relevant columns for this table:

| index  | session_id | value |
| -- | -- | -- |
| 0 | 0 | 0.0 |
| 1 | 0 | 5.0 |
| 2 | 0 | 10.0 |
| 3 | 0 | 15.0 |
| 4 | 0 | 20.0 |
| 5 | 1 | 0.0 |
| 6 | 1 | 1.0 |
| 7 | 1 | 2.0 |
| 8 | 1 | 3.0 |
| 9 | 2 | 0.0 |
| 10 | 3 | 0.0 |
| 11 | 3 | 5.0 |
| 12 | 4 | 0.0 |
| 13 | 4 | 7.0 |
| 14 | 4 | 14.0 |
| 15 | 5 | NaN |
| 16 | 5 | NaN |

Calcualting DIFF(value) for all rows should return these values:
`[NaN, 5, 5, 5, 5, -20, 1, 1, 1, -3, 0, 5, -5, 7, 7, NaN, NaN]`

And when I ran this code, I got that result:
```python
import featuretools as ft
from featuretools.tests.testing_utils import make_ecommerce_entityset

es = make_ecommerce_entityset()
diff_feature = ft.Feature(es["log"]["value"], primitive=ft.primitives.Diff)
fm = ft.calculate_feature_matrix(features=[diff_feature], entityset=es)
```
However, if I calculated each row at a different time, every value was `NaN`.

```python
import pandas as pd

cutoff_time_df = pd.DataFrame({'id': range(17), 'datetime': pd.date_range(start="2012-01-01", periods=17)})
fm_2 = ft.calculate_feature_matrix(features=[diff_feature], entityset=es, cutoff_time=cutoff_time_df)
```
All of the log entries occur before 2012 so the issue was not that the data was being filtered out due to occurring after the cutoff time.  What was going on is a result of how featuretools calculates behind the scenes.  Featuretools calculates all rows that share the same cutoff time together.  Unless a primitive specifies that it needs additional data via the `uses_full_entity` attribute, the data used will be limited to data related to the rows Featuretools is currently calculated for. 

`Diff` did not have the `uses_full_entity` attribute.  For the first feature matrix, every row shared the same cutoff time, so `Diff` had the full `value` column available to transform. In the second feature matrix calculation, each row was calculated at a different time, so the `value` column the `Diff` primitive saw was filtered so it only contained that row.  Transforming the first row of a column using `Diff` returns `NaN`, so each row was computed to be `NaN` due to how the data was filtered.

Setting `uses_full_entity` attribute to `True` for `Diff` caused the results for the second feature matrix to match the first. PR #824 added `uses_full_entity` to `Diff`

I hope that explanation helps, let me know if you have questions

**Comment by rwedge** [comment]
To respond to your scenario, @rightx2 

Using current featuretools release (no `uses_full_entity`)
We are looking at how the `DIFF(MAX(sales.amount))` feature was calculated for store 10 on the date 2017-05-01.
`Diff` has access to the values of MAX(sale.amount) for store 10 and every other store that was also calculated at 2017-05-01.  If you filter the stores entity dataframe to only contain rows from the stores calculated at this time, the store in the row above store 10 should have been used, and its `MAX(sale.amount)` should be 16571.428.

In the `uses_full_entity` case, the calculation should be the `MAX(sale.amount)` for store 10 on 2017-05-01 subtracted from the `MAX(sale.amount)` for the store directly above store 10 in the stores dataframe on 2017-05-01

**Comment by soliverc** [comment]
But how could the difference in John's health and Mary's health be a useful feature? Let's say we are predicting cancer. How would the health difference between two unrelated patients mean anything?

**Comment by rwedge** [comment]
Correct, it might not be a useful feature.  It may make sense to filter out that feature or to not use the Diff primitive.

**Comment by rightx2** [comment]
Now I understand... I agree with @soliverc ...Is there any situation that `DIFF` is useful? Perhaps, only having one `session-id` is the case where `DIFF` can be useful.

**Comment by rightx2** [comment]
@rwedge One more question. How can I set `uses_full_entity` to be `False. What I've did:
```
prim = ft.primitives.Diff()
prim.uses_full_entity = False
```

If it is the only way, I think it might be better to use like `Diff(uses_full_entity=True)`..?

**Comment by soliverc** [comment]
Does this also happen with transaction data? Will diff compare two unrelated customers purchases against eachother?

**Comment by rwedge** [comment]
Which table diff is being applied to does not change how the primitive is calculated.  Diff will compare unrelated customer purchases if the purchases are neighboring rows in the data.  If you would like to group transactions by customer so that Diff is only calculating for a particular customer's purchases, you can use Diff as a `GroupByTransformFeature` instead of a `TransformFeature`.  To use my previous example,

```python
ft.Feature(es['log']['value'], groupby=es['log']['session_id'], primitive=ft.primitives.Diff)
```

would create
```python-trace
<Feature: DIFF(value) by session_id>
```
which would group the log entries by session before applying Diff so that Diff considers each session's log entries separately.

If you want DFS to create groupby transform features using Diff you can add it to the `groupby_trans_primitives` list instead of `trans_primitives`.

**Comment by soliverc** [comment]
Yes definitely it makes much more sense to group by customer and calculate features. 

So now I've just replaced `trans_primitives` with `groupby_trans_primitives` when generating features. And I have removed `diff` altogether. 
```python

trans_primitives = ['day', 'month', 'is_weekend', 'time_since_previous']

# create features
feature_matrix, feature_defs = ft.dfs(entityset=es, target_entity='clients',  
                                      agg_primitives = agg_primitives,
                                      groupby_trans_primitives = trans_primitives, # change to group
                                      max_depth = 2, features_only = False,
                                      ignore_variables={'clients':rem_cols})
```

**Comment by soliverc** [comment]
Do I need to do the same for `agg_primitives`?

For example with these features:
```python

# agg features used: ['sum', 'time_since_last','time_since_first', 'avg_time_between', 'mode', 'num_unique', 'min', 'last', 'mean', 'max', 'count','median']

# generated agg features:

'MODE(transactions.MONTH(local_date))',
 'MODE(transactions.MONTH(local_date) by ibannumber)',
```
In this case `ibannumber` is my unique identifier. I seem to have two versions of `MODE` here.

**Comment by rwedge** [comment]
Usually `GroupByTransformFeatures` are used for transform primitives that rely on more data than the just a single row of the table (DIFF, TimeSincePrevious, CumMean, etc)

The `Month` primitive extracts the month for a datetime field. It only needs to look at the current transaction.  The filtering by customer is done when the aggregation primitive  (in this case Mode) is stacked on top of it.

Here there are two version of Month, one as a transform feature and one as a groupby transform feature, but the values are the same because grouping doesn't impact the value of Month

This is starting to move away from the original issue, I could answer more questions in our [slack channel](https://join.slack.com/t/featuretools/shared_invite/enQtNTEwODEzOTEwMjg4LTQ1MjZlOWFmZDk2YzAwMjEzNTkwZTZkN2NmOGFjOGI4YzE5OGMyMGM5NGIxNTE4NjkzYWI3OWEwZjkyZGExYmQ)

**Comment by soliverc** [comment]
> Here there are two version of Month, one as a transform feature and one as a groupby transform feature, but the values are the same because grouping doesn't impact the value of Month

So any time I generate features it also generates duplicate columns, even though I only specify groupby transforms? Is this a bug surely? 

I've added a question to slack also. 

![image](https://user-images.githubusercontent.com/47222261/69362304-30142900-0c86-11ea-879f-5ec749f400a6.png)

**Comment by soliverc** [comment]
In case anybody else googles themselves here, I re-ran it and set `trans_primitives=[`], this seems to have gotten rid of the duplicate columns.

**Comment by rwedge** [comment]
#824 updated how Diff is calculated, I'm going ahead and closing this issue
