### ISSUE TITLE
Test dask implementation on home credit notebook

### ISSUE THREAD

**Issue by rwedge** [FeatureLabs/featuretools#884]
Original Notebooks:
https://github.com/Featuretools/Automated-Manual-Comparison/blob/master/Loan%20Repayment/notebooks/Automated%20Loan%20Repayment.ipynb

https://github.com/Featuretools/Automated-Manual-Comparison/blob/master/Loan%20Repayment/notebooks/Featuretools%20on%20Dask.ipynb

**Comment by kmax12** [comment]
@thehomebrewnerd can you add link to the homecredit notebook?

**Comment by thehomebrewnerd** [comment]
@kmax12 Added links in the issue description above.

**Comment by thehomebrewnerd** [comment]
Performed two rounds of benchmarking using different primitives.

First benchmark: and (trans), sum (agg), max (agg) - 938 features
New Implementation
-Read Data: <1s
-Clean Data: <1s
-Partition Data: 0s
-Create Entityset: <1s
-Run DFS: 128s
-Compute FM: 190s
**TOTAL: 319s**

Original Notebook
-Read Data: 53s
-Clean Data: 27s
-Partition Data: 1006s
-Create Entityset: <1s
-Run DFS: <1s
-Compute FM: 183s
**TOTAL: 1270s**

Second benchmark: and (trans), sum (agg), max (agg), min (agg), mean (agg) - 1545 features
New Implementation
-Read Data: <1s
-Clean Data: <1s
-Partition Data: 0s
-Create Entityset: <1s
-Run DFS: 169s
-Compute FM: 815s
**TOTAL: 985s**

Original Notebook
-Read Data: 53s
-Clean Data: 27s
-Partition Data: 1006s
-Create Entityset: <1s
-Run DFS: <1s
-Compute FM: 310s
**TOTAL: 1396s**

To date, I have not been able to successfully generate more features than the second benchmark. The first benchmark was run using `client=Client()` which created 4 workers with 4GB memory each. The second benchmark was run using `client=Client(n_workers=1)` which created a single worker with 16GB of memory. The second benchmark would not run successfully with 4 workers. Note, the feature matrix generated by the second benchmark was approximately 3.1 GB in size when read in as a pandas dataframe.

**Comment by thehomebrewnerd** [comment]
Found some issues that seem to be related to partition size as well as attempting to compute to many aggregation features at once. Updated FeatureSetCalculator based on these issues and was able to generate a feature matrix with 1636 features using 4 workers with 4GB memory each using these primitives: and (trans), sum (agg), max (agg), min (agg), mean (agg), count (agg), any (agg), all (agg)

New Implementation
-Read Data: <1s
-Clean Data: <1s
-Partition Data: 0s
-Create Entityset: <1s
-Run DFS: 15s
-Save to CSV: 900s
TOTAL: 916s

Original Notebook
-Read Data: 53s
-Clean Data: 27s
-Partition Data: 1006s
-Create Entityset: <1s
-Run DFS: 1s
-Save to CSV: 661s
TOTAL: 1749s

Although the run with the new dask implementation has been completed successfully, it seems to be somewhat unreliable. Sometimes the run will fail and several worker high memory warnings are generated. There are also occasional errors generated related to unpickling coming from Dask.

Attempting to generate larger feature matrices by adding additional transform primitives still results in failures due to memory issues. These failures may be due to a complex dask task graph being generated by all of the merge operations that take place during calculation of the aggregation features.

**Comment by thehomebrewnerd** [comment]
Four different benchmark runs have been completed with various primitive combinations. The results are summarized in the file linked below.

[https://app.zenhub.com/files/102908804/d9db7c3a-1bc5-40f1-b61f-3ccd51e14bee/download](https://app.zenhub.com/files/102908804/d9db7c3a-1bc5-40f1-b61f-3ccd51e14bee/download)

**Comment by thehomebrewnerd** [comment]
Closed by #953
