### ISSUE TITLE
Review usage of len() call in Entityset.add_relationship()

### ISSUE THREAD

**Issue by thehomebrewnerd** [FeatureLabs/featuretools#903]
A `len()` call is used in `Entityset.add_relationship()` in an `if` statement to check if the child dataframe is empty. In the current dask implementation this code is commented out, and this did not cause any existing tests to fail. This code should be reviewed and updated if this check is needed.

**Comment by frances-h** [comment]
This doesn't get hit by any of our tests, but the `len` call in question does cover an edge case. It's needed to handle trying to add a relationship between an empty and non-empty entity on a numeric variable. Without the check, adding the relationship fails since Pandas defaults empty Series to `object` dtype.

If we decide that we do not support having empty entity dataframes with Dask, we can keep the `len` call for Pandas and skip for Dask without any issues. 

As an example, this currently fails with the check in `add_relationship` commented out:
```python
df1 = pd.DataFrame({
    'id': range(4),
})

df2 = pd.DataFrame(columns=['id', 'val'])

es = ft.EntitySet("test")
es.entity_from_dataframe(entity_id="entity1",
                         dataframe=df1,
                         index="id")
es.entity_from_dataframe(entity_id="entity2",
                         dataframe=df2,
                         index='id')

es.add_relationship(ft.Relationship(es["entity1"]["id"], es["entity2"]["val"]))

--> ValueError: Unable to add relationship because id in entity1 is Pandas dtype int64 and val in entity2 is Pandas dtype object.
```
