### ISSUE TITLE
Creating feature with multi time step behind

### ISSUE THREAD

**Issue by dfayzur** [FeatureLabs/featuretools#98]
Thank you very much for the tools. 

I would like to build multi time step behind feature from a time stamp. I just checking if there is any example / manual for doing this.

For example, I have the following table:

My table>
row_id, id, time, purchase
1, id1, 2016-01-12 13:00:00, 10
2, id1, 2016-01-12 14:00:00, 15
3, id1, 2016-01-12 15:00:00, 20
4, id1, 2016-01-12 16:00:00, 25
5, id2, 2016-01-12 16:00:00, 13
6, id2, 2016-01-12 16:00:00, 17
7, id2, 2016-01-12 16:00:00, 19

The output I wish to have is: for each time I like to calculate the average of last two hours purchase average. The output for example:

row_id, id, time, average_purchase
1, id1, 2016-01-12 13:00:00, NA
2, id1, 2016-01-12 14:00:00, 5
3, id1, 2016-01-12 15:00:00, 12.5
4, id1, 2016-01-12 16:00:00, 17.5
5, id2, 2016-01-12 16:00:00, NA
6, id2, 2016-01-12 16:00:00, 6.5
7, id2, 2016-01-12 16:00:00, 15

Thanks in advance,
Fayzur

**Comment by bschreck** [comment]
Hi Fayzur,

Take a look at the CumMean feature. You can set a "use_previous" flag on it to only use the previous 2 hours of data. In your case, you'd want to set the "group_feature" feature to the "row_id" column.

Something like this:

```
CumMean(Feature(es['your_entity']['average_purchase']), group_feature=Feature(es['your_entity']['row_id']), use_previous='2 hours')
```

However, this will include the value of the row itself. We don't currently have functionality to move the window of time in "use_previous" backward. So row 4 for instance would return 20 instead of 17.5. A more complicated solution that would be able to do this is to use `normalize_entity` to create a new entity indexed by row_id, and then use the `Mean()` aggregation feature aggregating the average_purchase column from the new entity. In this case, you could pass in your own custom cutoff times, and the `training_window` parameter to `ft.calculate_feature_matrix`.

Let me know if you have any more questions!

**Comment by dfayzur** [comment]
Hello @bschreck, 
Thank you very much for quick reply. I really appreciate it. 

Per your suggestion, I will implement it and come back to you if I need any more help.

**Comment by kmax12** [comment]
Closing this issue for now since it's been open for a while and there doesn't seem to be strong need for this. If anyone comes across this and can share more info about their use case, feel free to comment and reopen.
